// SPDX-License-Identifier: MIT
import {
  ArrowDown,
  ArrowDownAZ,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ClipboardList,
  ClipboardPaste,
  Clock,
  CloudDownload,
  CloudUpload,
  Columns,
  Copy,
  CopyPlus,
  Database,
  Eraser,
  FileCode,
  FileJson,
  FilePenLine,
  FilePlus,
  FilePlus2,
  FileSpreadsheet,
  FileText,
  FileType,
  Filter,
  FilterX,
  FolderClock,
  FolderOpen,
  FunctionSquare,
  GitCompare,
  Globe,
  Hash,
  History,
  Image,
  Info,
  Keyboard,
  Locate,
  LogOut,
  MessageSquare,
  Move,
  PaintBucket,
  Palette,
  Pencil,
  Plus,
  Redo2,
  RefreshCw,
  Replace,
  RotateCcw,
  Ruler,
  Save,
  Search,
  Settings,
  Sparkles,
  Table,
  TextSelect,
  Trash2,
  Undo2,
  Wand2,
  X,
  type IconNode,
} from 'lucide';
import type { CommandId } from '../app/commands';

/**
 * Leading icons for plain (non-checkable) command items, filling the same
 * reserved left-hand column the checkmark uses for toggle/radio items (#393)
 * — the two are mutually exclusive per item, so no extra width is added.
 * Checkable items (Bold/Italic/Underline, wrap, zoom levels, theme, etc.)
 * intentionally have no entry here: their checkmark already communicates
 * state in that same slot. Not every command has an obvious icon; those are
 * simply omitted; the slot stays empty, exactly as it was before.
 *
 * Shared by the menu bar and every context menu (the grid's, the document
 * tabs', and the worksheet strip's), so a command shows the same icon in
 * each.
 */
export const ICON_BY_COMMAND: Partial<Record<CommandId, IconNode>> = {
  'file.new': FilePlus,
  'file.newCsv': FilePlus2,
  'file.open': FolderOpen,
  'file.openRecent': FolderClock,
  'drive.open': CloudDownload,
  'drive.save': CloudUpload,
  'drive.saveAs': CloudUpload,
  'drive.signOut': LogOut,
  'file.reopen': RotateCcw,
  'sheet.convert': FileCode,
  'file.save': Save,
  'file.saveOptions': Settings,
  'sheet.exportCsv': FileText,
  'sheet.exportXlsx': FileSpreadsheet,
  'sheet.exportJson': FileJson,
  'app.settings': Settings,
  'file.closeTab': X,
  'edit.undo': Undo2,
  'edit.redo': Redo2,
  'edit.copy': Copy,
  'edit.copyScreenshot': Image,
  'edit.copyAsMarkdown': FileCode,
  'edit.paste': ClipboardPaste,
  'edit.selectAll': TextSelect,
  'edit.insertCopiedCells': ClipboardList,
  'edit.insertCopiedRows': Table,
  'edit.insertCopiedCols': Columns,
  'edit.fillDown': ArrowDownToLine,
  'edit.flashFill': Wand2,
  'edit.moveRange': Move,
  'edit.revertCell': RotateCcw,
  'edit.revertAll': History,
  'search.find': Search,
  'search.replace': Replace,
  'search.findNext': ChevronRight,
  'search.findPrev': ChevronLeft,
  'search.goToCell': Locate,
  'sheet.recalculate': RefreshCw,
  'sheet.timezone': Clock,
  'sheet.displayLanguage': Globe,
  'sheet.versionHistory': History,
  'sheet.clearVersionHistory': Trash2,
  'worksheet.add': Plus,
  'worksheet.addMarkdown': FilePenLine,
  'worksheet.addJson': FileJson,
  'worksheet.addYaml': FileCode,
  'worksheet.addText': FileType,
  'worksheet.rename': Pencil,
  'worksheet.duplicate': CopyPlus,
  'worksheet.delete': Trash2,
  'worksheet.next': ChevronRight,
  'worksheet.prev': ChevronLeft,
  'worksheet.moveFirst': ChevronsLeft,
  'worksheet.moveLeft': ArrowLeft,
  'worksheet.moveRight': ArrowRight,
  'worksheet.moveLast': ChevronsRight,
  'tab.moveFirst': ChevronsLeft,
  'tab.moveLeft': ArrowLeft,
  'tab.moveRight': ArrowRight,
  'tab.moveLast': ChevronsRight,
  'sheet.insertRowAbove': ArrowUp,
  'sheet.insertRowBelow': ArrowDown,
  'sheet.deleteRows': Trash2,
  'sheet.insertColLeft': ArrowLeft,
  'sheet.insertColRight': ArrowRight,
  'sheet.deleteCols': Trash2,
  'sheet.autoFitCols': Ruler,
  'sheet.filter': Filter,
  'sheet.filterClear': FilterX,
  'sheet.sort': ArrowDownAZ,
  'sheet.sortClear': ArrowUpDown,
  'format.textColor': Palette,
  'format.backgroundColor': PaintBucket,
  'format.borders': Table,
  'format.numberFormat': Hash,
  'format.conditionalFormatting': Sparkles,
  'format.clear': Eraser,
  'data.runSqlQuery': Database,
  'data.compareDiff': GitCompare,
  'data.validation': CheckSquare,
  'data.comment': MessageSquare,
  'help.formula': FunctionSquare,
  'help.shortcuts': Keyboard,
  'help.about': Info,
};
