// SPDX-License-Identifier: MIT
import {
  ArrowDown,
  BringToFront,
  ChartColumn,
  Circle,
  Minus,
  MoveUpRight,
  SendToBack,
  Shapes,
  Image as ImageIcon,
  Square,
  ArrowDownAZ,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  CalendarDays,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ClipboardList,
  ClipboardPaste,
  ClipboardType,
  Clock,
  CloudDownload,
  CloudUpload,
  Columns,
  Copy,
  CopyPlus,
  Database,
  DollarSign,
  Eraser,
  FileCode,
  FileJson,
  FilePenLine,
  Grid3x3,
  FilePlus,
  FilePlus2,
  FileSpreadsheet,
  FileText,
  FileType,
  Filter,
  FilterX,
  FolderClock,
  FolderOpen,
  FunctionSquare,
  GitCompare,
  Globe,
  Hash,
  History,
  Image,
  Info,
  Keyboard,
  ListChecks,
  ListFilter,
  Locate,
  LogOut,
  MessageSquare,
  Move,
  Paintbrush,
  PaintBucket,
  Palette,
  FolderInput,
  FolderPlus,
  Pencil,
  Percent,
  Plus,
  Printer,
  Redo2,
  RefreshCw,
  Replace,
  RotateCcw,
  Ruler,
  Save,
  Scissors,
  Search,
  Settings,
  Settings2,
  Sparkles,
  Table,
  TextSelect,
  Type,
  Trash2,
  Undo2,
  Wand2,
  X,
  type IconNode,
} from 'lucide';
import type { CommandId } from '../app/commands';

/**
 * Leading icons for plain (non-checkable) command items, filling the same
 * reserved left-hand column the checkmark uses for toggle/radio items (#393)
 * — the two are mutually exclusive per item, so no extra width is added.
 * Checkable items (Bold/Italic/Underline, wrap, zoom levels, theme, etc.)
 * intentionally have no entry here: their checkmark already communicates
 * state in that same slot. Not every command has an obvious icon; those are
 * simply omitted; the slot stays empty, exactly as it was before.
 *
 * Shared by the menu bar and every context menu (the grid's, the document
 * tabs', and the worksheet strip's), so a command shows the same icon in
 * each.
 */
export const ICON_BY_COMMAND: Partial<Record<CommandId, IconNode>> = {
  'file.new': FilePlus,
  'file.newCsv': FilePlus2,
  'file.open': FolderOpen,
  'file.openRecent': FolderClock,
  'drive.open': CloudDownload,
  'drive.save': CloudUpload,
  'drive.saveAs': CloudUpload,
  'drive.signOut': LogOut,
  'file.reopen': RotateCcw,
  'sheet.convert': FileCode,
  'file.save': Save,
  'file.saveOptions': Settings,
  'sheet.exportCsv': FileText,
  'sheet.exportXlsx': FileSpreadsheet,
  'sheet.exportJson': FileJson,
  'app.settings': Settings,
  'file.print': Printer,
  'file.closeTab': X,
  'edit.undo': Undo2,
  'edit.redo': Redo2,
  'edit.cut': Scissors,
  'edit.copy': Copy,
  'edit.copyScreenshot': Image,
  'edit.copyAsMarkdown': FileCode,
  'edit.paste': ClipboardPaste,
  'edit.pasteValues': ClipboardType,
  'edit.pasteFormats': Paintbrush,
  'edit.insertDate': CalendarDays,
  'edit.insertTime': Clock,
  'edit.selectAll': TextSelect,
  'edit.insertCopiedCells': ClipboardList,
  'edit.insertCopiedRows': Table,
  'edit.insertCopiedCols': Columns,
  'edit.fillDown': ArrowDownToLine,
  'edit.flashFill': Wand2,
  'edit.moveRange': Move,
  'edit.revertCell': RotateCcw,
  'edit.revertAll': History,
  'search.find': Search,
  'search.replace': Replace,
  'search.findNext': ChevronRight,
  'search.findPrev': ChevronLeft,
  'search.goToCell': Locate,
  'sheet.recalculate': RefreshCw,
  'sheet.timezone': Clock,
  'sheet.displayLanguage': Globe,
  'sheet.versionHistory': History,
  'sheet.clearVersionHistory': Trash2,
  'worksheet.add': Plus,
  'worksheet.addPaper': Grid3x3,
  'worksheet.addMarkdown': FilePenLine,
  'worksheet.addJson': FileJson,
  'worksheet.addYaml': FileCode,
  'worksheet.addText': FileType,
  'worksheet.addFromCsv': FileSpreadsheet,
  'worksheet.rename': Pencil,
  'worksheet.tabColor': Palette,
  'worksheet.newFolder': FolderPlus,
  'worksheet.moveToFolder': FolderInput,
  'worksheet.duplicate': CopyPlus,
  'worksheet.delete': Trash2,
  'worksheet.next': ChevronRight,
  'worksheet.prev': ChevronLeft,
  'worksheet.moveFirst': ChevronsLeft,
  'worksheet.moveLeft': ArrowLeft,
  'worksheet.moveRight': ArrowRight,
  'worksheet.moveLast': ChevronsRight,
  'tab.moveFirst': ChevronsLeft,
  'tab.moveLeft': ArrowLeft,
  'tab.moveRight': ArrowRight,
  'tab.moveLast': ChevronsRight,
  'sheet.insertRowAbove': ArrowUp,
  'sheet.insertRowBelow': ArrowDown,
  'sheet.deleteRows': Trash2,
  'sheet.insertColLeft': ArrowLeft,
  'sheet.insertColRight': ArrowRight,
  'sheet.deleteCols': Trash2,
  'sheet.autoFitCols': Ruler,
  'sheet.filter': Filter,
  'sheet.headerFilter': ListFilter,
  'sheet.filterClear': FilterX,
  'sheet.sort': ArrowDownAZ,
  'sheet.sortClear': ArrowUpDown,
  'format.font': Type,
  'view.customizeToolbar': Settings2,
  'format.textColor': Palette,
  'format.backgroundColor': PaintBucket,
  'format.borders': Table,
  'format.numberFormat': Hash,
  'format.conditionalFormatting': Sparkles,
  'format.clear': Eraser,
  'format.presetNumber': Hash,
  'format.presetCurrency': DollarSign,
  'format.presetPercent': Percent,
  'data.runSqlQuery': Database,
  'data.compareDiff': GitCompare,
  'data.validation': CheckSquare,
  'data.checkValidation': ListChecks,
  'data.comment': MessageSquare,
  'insert.rectangle': Square,
  'insert.ellipse': Circle,
  'insert.line': Minus,
  'insert.arrow': MoveUpRight,
  'insert.textBox': Type,
  'insert.image': ImageIcon,
  'insert.chart': ChartColumn,
  'insert.objectList': Shapes,
  'object.bringToFront': BringToFront,
  'object.sendToBack': SendToBack,
  'help.formula': FunctionSquare,
  'help.shortcuts': Keyboard,
  'help.about': Info,
};
