// @generated by scripts/embed-model.mjs — do not edit.
// The vendored "smollm2-135m-instruct-gguf" local-assistant model (see docs/llm-model.md),
// embedded as chunked Base64 so the distribution needs no network access.
// Each entry's chunks are decoded and concatenated, then verified against
// `sha256`, before being written into Cache Storage — see
// src/app/llm/cache-prepopulate.ts.

import type { ModelFileEntry } from '../../app/llm/model-file-entry';

import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_0 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part000';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_1 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part001';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_2 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part002';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_3 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part003';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_4 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part004';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_5 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part005';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_6 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part006';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_7 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part007';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_8 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part008';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_9 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part009';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_10 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part010';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_11 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part011';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_12 } from './model-payload/SmolLM2-135M-Instruct-Q4_K_M.gguf.part012';

export type { ModelFileEntry };

export const MODEL_FILES: readonly ModelFileEntry[] = [
  {
    name: 'SmolLM2-135M-Instruct-Q4_K_M.gguf',
    byteLength: 105454432,
    sha256: '2e8040ceae7815abe0dcb3540b9995eaa1fa0d2ca9e797d0a635ae4433c68c2d',
    chunks: [chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_0, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_1, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_2, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_3, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_4, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_5, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_6, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_7, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_8, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_9, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_10, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_11, chunk_SmolLM2_135M_Instruct_Q4_K_M_gguf_12],
  },
];
