// @generated by scripts/embed-model.mjs — do not edit.
// The vendored "gemma3-270m-ja" local-assistant model (see docs/llm-model.md),
// embedded as chunked Base64 so the distribution needs no network access.
// Each entry's chunks are decoded and concatenated, then verified against
// `sha256`, before being written into Cache Storage — see
// src/app/llm/cache-prepopulate.ts.

import type { ModelFileEntry } from '../app/llm/model-file-entry';

import { CHUNK_BASE64 as chunk_mlc_chat_config_json_0 } from './model-payload/mlc-chat-config.json.part000';
import { CHUNK_BASE64 as chunk_tensor_cache_json_0 } from './model-payload/tensor-cache.json.part000';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_0 } from './model-payload/params_shard_0.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_1 } from './model-payload/params_shard_0.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_2 } from './model-payload/params_shard_0.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_3 } from './model-payload/params_shard_0.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_4 } from './model-payload/params_shard_0.bin.part004';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_5 } from './model-payload/params_shard_0.bin.part005';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_6 } from './model-payload/params_shard_0.bin.part006';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_7 } from './model-payload/params_shard_0.bin.part007';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_8 } from './model-payload/params_shard_0.bin.part008';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_9 } from './model-payload/params_shard_0.bin.part009';
import { CHUNK_BASE64 as chunk_params_shard_1_bin_0 } from './model-payload/params_shard_1.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_1_bin_1 } from './model-payload/params_shard_1.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_1_bin_2 } from './model-payload/params_shard_1.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_1_bin_3 } from './model-payload/params_shard_1.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_2_bin_0 } from './model-payload/params_shard_2.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_2_bin_1 } from './model-payload/params_shard_2.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_2_bin_2 } from './model-payload/params_shard_2.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_2_bin_3 } from './model-payload/params_shard_2.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_3_bin_0 } from './model-payload/params_shard_3.bin.part000';
import { CHUNK_BASE64 as chunk_tokenizer_json_0 } from './model-payload/tokenizer.json.part000';
import { CHUNK_BASE64 as chunk_tokenizer_json_1 } from './model-payload/tokenizer.json.part001';
import { CHUNK_BASE64 as chunk_tokenizer_json_2 } from './model-payload/tokenizer.json.part002';
import { CHUNK_BASE64 as chunk_tokenizer_json_3 } from './model-payload/tokenizer.json.part003';
import { CHUNK_BASE64 as chunk_gemma3_270m_japanese_q4f32_1_ctx4k_webgpu_wasm_0 } from './model-payload/gemma3-270m-japanese-q4f32_1-ctx4k-webgpu.wasm.part000';

export type { ModelFileEntry };

export const MODEL_FILES: readonly ModelFileEntry[] = [
  {
    name: 'mlc-chat-config.json',
    byteLength: 3597,
    sha256: '4f885abea0dcbd59fc801fcbb5a12385ec0b535720b7e375e59322a69d639f63',
    chunks: [chunk_mlc_chat_config_json_0],
  },
  {
    name: 'tensor-cache.json',
    byteLength: 128507,
    sha256: 'a2fcf3efed117dbae70bfb2068a93d5a053d6818487d9c1aa010a1c23fe02a7a',
    chunks: [chunk_tensor_cache_json_0],
  },
  {
    name: 'params_shard_0.bin',
    byteLength: 83886080,
    sha256: 'f0946afe803d4428fd4b1162db0a8d23d7497e03bb99ae7ac71f17e8a0f89c84',
    chunks: [chunk_params_shard_0_bin_0, chunk_params_shard_0_bin_1, chunk_params_shard_0_bin_2, chunk_params_shard_0_bin_3, chunk_params_shard_0_bin_4, chunk_params_shard_0_bin_5, chunk_params_shard_0_bin_6, chunk_params_shard_0_bin_7, chunk_params_shard_0_bin_8, chunk_params_shard_0_bin_9],
  },
  {
    name: 'params_shard_1.bin',
    byteLength: 33201408,
    sha256: '878c480b1e0e8a4082ac8a305293361a6ba726ef0b0fb7db3de12f336a7a44ca',
    chunks: [chunk_params_shard_1_bin_0, chunk_params_shard_1_bin_1, chunk_params_shard_1_bin_2, chunk_params_shard_1_bin_3],
  },
  {
    name: 'params_shard_2.bin',
    byteLength: 33336064,
    sha256: '1b4d339350067464be4edaf82d784835f6842b1820dae530459b5e3daae69323',
    chunks: [chunk_params_shard_2_bin_0, chunk_params_shard_2_bin_1, chunk_params_shard_2_bin_2, chunk_params_shard_2_bin_3],
  },
  {
    name: 'params_shard_3.bin',
    byteLength: 462080,
    sha256: '793146d01e4282bd9ba31abfaaad74b759add0f695bd6dbed94732e6cb67f918',
    chunks: [chunk_params_shard_3_bin_0],
  },
  {
    name: 'tokenizer.json',
    byteLength: 33384568,
    sha256: '4667f2089529e8e7657cfb6d1c19910ae71ff5f28aa7ab2ff2763330affad795',
    chunks: [chunk_tokenizer_json_0, chunk_tokenizer_json_1, chunk_tokenizer_json_2, chunk_tokenizer_json_3],
  },
  {
    name: 'gemma3-270m-japanese-q4f32_1-ctx4k-webgpu.wasm',
    byteLength: 5664330,
    sha256: '80286c3ecc2b6cdd3bb5eaa081d55acfdd69a15c2eac09d49ddcb53beaafe155',
    chunks: [chunk_gemma3_270m_japanese_q4f32_1_ctx4k_webgpu_wasm_0],
  },
];
