// @generated by scripts/embed-wasm.mjs — do not edit.
/* tslint:disable */
/* eslint-disable */
/**
 * Parse CSV structure at the byte level. Never modifies or normalizes the
 * input; text decoding stays on the JavaScript side.
 */
export function parseCsv(bytes: Uint8Array, delimiter: number, treat_utf8_bom: boolean): ParseIndex;
/**
 * Delimiter sniffing over the first 64 KiB (outside quoted regions).
 */
export function sniffDelimiter(bytes: Uint8Array): number;
/**
 * Serialization planning: ordered `[kind, a, b]` triples describing the
 * output as verbatim copies of the original bytes plus payload segments.
 */
export function planReplacements(bytes_len: number, ranges: Uint32Array, payload_lens: Uint32Array): Uint32Array;
/**
 * Apply byte-range replacements to the original bytes. Bytes outside the
 * replaced ranges are copied verbatim.
 */
export function applyReplacements(bytes: Uint8Array, ranges: Uint32Array, payload: Uint8Array, payload_lens: Uint32Array): Uint8Array;
/**
 * Raw DEFLATE compression for the `.rcsv` container payload.
 */
export function rcsvDeflate(bytes: Uint8Array): Uint8Array;
/**
 * Raw DEFLATE decompression, bounded by `max_len` output bytes (a
 * decompression-bomb guard). Returns an empty array on failure; the caller
 * distinguishes "empty payload" via the container's stored length.
 */
export function rcsvInflate(bytes: Uint8Array, max_len: number): Uint8Array | undefined;
/**
 * CRC-32 (IEEE) checksum of the container's uncompressed body.
 */
export function rcsvCrc32(bytes: Uint8Array): number;
/**
 * Reduce finite numbers to `[sum, min, max]` for selection statistics.
 */
export function statsAggregate(values: Float64Array): Float64Array;
/**
 * Count non-overlapping occurrences of `needle` in `haystack` (literal search).
 */
export function countLiteral(haystack: Uint8Array, needle: Uint8Array): number;
/**
 * Structural index of one parsed CSV byte sequence. See `csv.rs` for the
 * array layouts (record/field/diagnostic strides).
 */
export class ParseIndex {
  private constructor();
  free(): void;
  readonly records: Uint32Array;
  readonly fields: Uint32Array;
  readonly diagnostics: Uint32Array;
  readonly crlf: number;
  readonly lf: number;
  readonly cr: number;
  readonly hasFinalNewline: boolean;
  readonly bomLength: number;
}

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
  readonly memory: WebAssembly.Memory;
  readonly __wbg_parseindex_free: (a: number, b: number) => void;
  readonly parseindex_records: (a: number) => [number, number];
  readonly parseindex_fields: (a: number) => [number, number];
  readonly parseindex_diagnostics: (a: number) => [number, number];
  readonly parseindex_crlf: (a: number) => number;
  readonly parseindex_lf: (a: number) => number;
  readonly parseindex_cr: (a: number) => number;
  readonly parseindex_hasFinalNewline: (a: number) => number;
  readonly parseindex_bomLength: (a: number) => number;
  readonly parseCsv: (a: number, b: number, c: number, d: number) => number;
  readonly sniffDelimiter: (a: number, b: number) => number;
  readonly planReplacements: (a: number, b: number, c: number, d: number, e: number) => [number, number];
  readonly applyReplacements: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
  readonly rcsvDeflate: (a: number, b: number) => [number, number];
  readonly rcsvInflate: (a: number, b: number, c: number) => [number, number];
  readonly rcsvCrc32: (a: number, b: number) => number;
  readonly statsAggregate: (a: number, b: number) => [number, number];
  readonly countLiteral: (a: number, b: number, c: number, d: number) => number;
  readonly __wbindgen_export_0: WebAssembly.Table;
  readonly __wbindgen_free: (a: number, b: number, c: number) => void;
  readonly __wbindgen_malloc: (a: number, b: number) => number;
  readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;
/**
* Instantiates the given `module`, which can either be bytes or
* a precompiled `WebAssembly.Module`.
*
* @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
*
* @returns {InitOutput}
*/
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
* If `module_or_path` is {RequestInfo} or {URL}, makes a request and
* for everything else, calls `WebAssembly.instantiate` directly.
*
* @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
*
* @returns {Promise<InitOutput>}
*/
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
