// SPDX-License-Identifier: MIT
/**
 * Local, read-only SQL analysis over one worksheet/CSV table at a time,
 * executed by sql.js (SQLite compiled to WebAssembly) — see
 * docs/architecture.md "The SQL query engine" for why this replaced an
 * earlier hand-written interpreter, and THIRD-PARTY-NOTICES.md for the
 * sql.js/SQLite license text.
 *
 * The sql.js WASM binary is embedded as Base64 (`../wasm-gen/sqljs-wasm-payload`,
 * generated by `scripts/embed-sqljs.mjs`) and instantiated from those decoded
 * bytes only — `locateFile()` is never set, so the engine never fetches a
 * `.wasm` file over the network, keeping `file://` usage working. Call
 * {@link initSqlEngine} once (see `src/main.ts`) before {@link runSqlQuery}.
 *
 * A query is accepted only when it is a single statement whose first
 * keyword is `SELECT` — no grammar production exists for anything else, so
 * `INSERT`/`UPDATE`/`DELETE`/`DROP`/`ATTACH`/`PRAGMA`/a second statement/etc.
 * are all rejected before the query ever reaches SQLite, by a tokenizer-based
 * check (not a keyword-blacklist substring search: string/quoted-identifier
 * contents and `--`/`/* *\/` comments are never mistaken for real tokens).
 * SQLite itself then executes the full query against an ephemeral, in-memory
 * database created fresh for each call and closed immediately after, so nested
 * subqueries, joins, CASE expressions, and the rest of SQLite's read-only SQL
 * dialect are all available (a strict superset of the old hand-written grammar).
 *
 * The caller (`src/app/commands/sql.ts`) maps the worksheet/CSV the user
 * picked in the UI to the plain `SqlTable` shape below and always queries it
 * through the fixed literal `data` in `FROM data` — a worksheet's *display*
 * name (which may contain spaces, quotes, or SQL keywords) is never used as
 * a SQL identifier, and user input is never concatenated into a query string
 * beyond wrapping the whole (already-gated) query as a read-only subquery.
 */

import initSqlJs, { type Database, type SqlJsStatic } from 'sql.js';
import { SQLJS_WASM_BASE64 } from '../wasm-gen/sqljs-wasm-payload';

// ----- Bounds (documented; mirrors the formula engine's bounds table in docs/security.md) -----

/** Maximum query text length, in UTF-16 code units. */
export const SQL_MAX_QUERY_LENGTH = 4096;
/** Maximum number of tokens the gate's tokenizer will scan before rejecting the query. */
export const SQL_MAX_TOKENS = 2000;
/** Maximum source rows loaded from the picked table into SQLite (see docs/performance.md). */
export const SQL_MAX_SOURCE_ROWS = 200_000;
/** Maximum result rows ever returned, regardless of the query's own LIMIT. */
export const SQL_MAX_RESULT_ROWS = 1000;

// ----- Public data model -----

/** A source table: the first row is always the header row. */
export interface SqlTable {
  headers: string[];
  rows: string[][];
}

/** A query result cell: a plain string, or a number for a numeric SQLite value. */
export type SqlValue = string | number;

export interface SqlQueryResult {
  /** Output column display names, left to right (SQLite's own naming: the expression text, or its alias). */
  columns: string[];
  rows: SqlValue[][];
  /** Rows in the source table that were available (before the query's own WHERE/LIMIT). */
  sourceRows: number;
  /** True when the source table itself was cut off at {@link SQL_MAX_SOURCE_ROWS}. */
  sourceTruncated: boolean;
  /** Total rows the query itself produced (respecting its own LIMIT, if any), before {@link SQL_MAX_RESULT_ROWS} capped the returned rows. */
  matchedRows: number;
  /** True when `rows` is shorter than `matchedRows` because {@link SQL_MAX_RESULT_ROWS} applied. */
  truncated: boolean;
}

/** A stable, localizable reason a query was rejected — see `sql.error.*` in the locale files. */
export type SqlErrorCode =
  | 'empty'
  | 'tooLong'
  | 'tooManyTokens'
  | 'unterminatedString'
  | 'unterminatedIdentifier'
  | 'unexpectedChar'
  | 'unsupportedStatement'
  | 'multipleStatements'
  | 'sqliteError'
  | 'engineUnavailable';

export interface SqlErrorLocation {
  /** 0-based UTF-16 offset into the query text. */
  offset: number;
}

/** A rejected or failed query. `code`/`params` drive localized `sql.error.*` messages; `message` is English, for logs/tests. */
export class SqlQueryError extends Error {
  readonly code: SqlErrorCode;
  readonly params: Record<string, string | number>;
  readonly location: SqlErrorLocation | null;

  constructor(
    code: SqlErrorCode,
    message: string,
    params: Record<string, string | number> = {},
    location: SqlErrorLocation | null = null,
  ) {
    super(message);
    this.name = 'SqlQueryError';
    this.code = code;
    this.params = params;
    this.location = location;
  }
}

// ----- Tokenizer -----
//
// Used for: the read-only/single-statement safety gate (assertReadOnlyQuery),
// the best-effort auto-formatter, and the keyword/function/column
// suggestions. Never used to evaluate a query — that is always SQLite's job.

type TokenType = 'ident' | 'qident' | 'number' | 'string' | 'punct' | 'eof';

interface Token {
  type: TokenType;
  /** Literal text (identifiers/strings already unescaped; punctuation verbatim). */
  text: string;
  /** Uppercased text, for case-insensitive keyword/identifier comparisons. */
  upper: string;
  offset: number;
}

const PUNCT_2 = ['<>', '!=', '<=', '>='];
const PUNCT_1 = ['(', ')', ',', '.', '*', '+', '-', '/', '=', '<', '>', ';'];

function tokenize(src: string): Token[] {
  const tokens: Token[] = [];
  let i = 0;
  const n = src.length;
  const push = (type: TokenType, text: string, offset: number) => {
    tokens.push({ type, text, upper: text.toUpperCase(), offset });
    if (tokens.length > SQL_MAX_TOKENS) {
      throw new SqlQueryError('tooManyTokens', `query has more than ${SQL_MAX_TOKENS} tokens`, {
        max: SQL_MAX_TOKENS,
      });
    }
  };
  while (i < n) {
    const c = src[i];
    if (c === ' ' || c === '\t' || c === '\n' || c === '\r') {
      i++;
      continue;
    }
    const start = i;
    // Line comment: -- to end of line.
    if (c === '-' && src[i + 1] === '-') {
      while (i < n && src[i] !== '\n') i++;
      continue;
    }
    // Block comment: /* ... */ (SQLite supports these; unterminated is treated as running to EOF).
    if (c === '/' && src[i + 1] === '*') {
      i += 2;
      while (i < n && !(src[i] === '*' && src[i + 1] === '/')) i++;
      i = i < n ? i + 2 : n;
      continue;
    }
    if (/[A-Za-z_]/.test(c)) {
      i++;
      while (i < n && /[A-Za-z0-9_]/.test(src[i])) i++;
      push('ident', src.slice(start, i), start);
      continue;
    }
    if (/[0-9]/.test(c) || (c === '.' && /[0-9]/.test(src[i + 1] ?? ''))) {
      i++;
      while (i < n && /[0-9]/.test(src[i])) i++;
      if (src[i] === '.') {
        i++;
        while (i < n && /[0-9]/.test(src[i])) i++;
      }
      push('number', src.slice(start, i), start);
      continue;
    }
    if (c === "'") {
      i++;
      let out = '';
      let closed = false;
      while (i < n) {
        if (src[i] === "'" && src[i + 1] === "'") {
          out += "'";
          i += 2;
          continue;
        }
        if (src[i] === "'") {
          i++;
          closed = true;
          break;
        }
        out += src[i];
        i++;
      }
      if (!closed) {
        throw new SqlQueryError('unterminatedString', 'unterminated string literal', {}, { offset: start });
      }
      push('string', out, start);
      continue;
    }
    if (c === '"') {
      i++;
      let out = '';
      let closed = false;
      while (i < n) {
        if (src[i] === '"' && src[i + 1] === '"') {
          out += '"';
          i += 2;
          continue;
        }
        if (src[i] === '"') {
          i++;
          closed = true;
          break;
        }
        out += src[i];
        i++;
      }
      if (!closed) {
        throw new SqlQueryError(
          'unterminatedIdentifier',
          'unterminated quoted identifier',
          {},
          { offset: start },
        );
      }
      push('qident', out, start);
      continue;
    }
    const two = src.slice(i, i + 2);
    if (PUNCT_2.includes(two)) {
      push('punct', two, start);
      i += 2;
      continue;
    }
    if (PUNCT_1.includes(c)) {
      push('punct', c, start);
      i += 1;
      continue;
    }
    throw new SqlQueryError('unexpectedChar', `unexpected character "${c}"`, { char: c }, { offset: start });
  }
  push('eof', '', n);
  return tokens;
}

// ----- Read-only / single-statement safety gate -----

/**
 * Reject anything that is not a single statement starting with `SELECT`.
 * Not a keyword-blacklist substring search: this tokenizes the query first
 * (so `--`/`/* *\/` comments and string/quoted-identifier contents can never
 * hide or fake a keyword), then checks only the token stream. `WITH`,
 * `EXPLAIN`, and `PRAGMA` are deliberately not accepted in this first
 * iteration — see docs/architecture.md — because safely proving a `WITH`
 * clause's final statement is a `SELECT` (SQLite allows `WITH ... INSERT/
 * UPDATE/DELETE`) needs real grammar-level parsing; a single leading `SELECT`
 * can never smuggle a DDL/DML statement, so it is the one shape this gate can
 * guarantee is read-only without parsing the rest of the query at all.
 */
function assertReadOnlyQuery(query: string): { body: string } {
  if (query.trim().length === 0) {
    throw new SqlQueryError('empty', 'the query is empty');
  }
  if (query.length > SQL_MAX_QUERY_LENGTH) {
    throw new SqlQueryError('tooLong', `query exceeds ${SQL_MAX_QUERY_LENGTH} characters`, {
      max: SQL_MAX_QUERY_LENGTH,
    });
  }
  const tokens = tokenize(query).filter((t) => t.type !== 'eof');
  if (tokens.length === 0) {
    throw new SqlQueryError('empty', 'the query is empty');
  }
  const first = tokens[0];
  if (first.type !== 'ident' || first.upper !== 'SELECT') {
    throw new SqlQueryError(
      'unsupportedStatement',
      'only a single, read-only SELECT query is supported',
      {},
      { offset: first.offset },
    );
  }
  const semiIndex = tokens.findIndex((t) => t.type === 'punct' && t.text === ';');
  let body = query;
  if (semiIndex !== -1) {
    if (semiIndex !== tokens.length - 1) {
      throw new SqlQueryError(
        'multipleStatements',
        'only one SELECT statement is allowed',
        {},
        { offset: tokens[semiIndex + 1].offset },
      );
    }
    body = query.slice(0, tokens[semiIndex].offset);
  }
  return { body };
}

/**
 * Structural syntax check only (tokenize + the read-only/single-statement
 * gate) — cheap enough to run on every keystroke for live feedback in the
 * editor. It does not bind the query against SQLite, so it cannot catch
 * semantic errors (an unknown column, a malformed expression); {@link
 * runSqlQuery} still performs the full check against real SQLite when the
 * query is actually run.
 */
export function checkSqlSyntax(query: string): SqlQueryError | null {
  try {
    assertReadOnlyQuery(query);
    return null;
  } catch (e) {
    if (e instanceof SqlQueryError) return e;
    throw e;
  }
}

// ----- Column naming (shared by table creation and formatting/suggestions) -----

/**
 * Deduplicate/normalize header text into safe, unique display names — never
 * the raw header text used as-is when blank or duplicate. An empty header
 * row (no columns at all) falls back to one placeholder column, since a
 * SQLite table needs at least one.
 */
function dedupeHeaderNames(headers: string[]): string[] {
  if (headers.length === 0) return ['column_1'];
  const names: string[] = [];
  const seen = new Set<string>();
  headers.forEach((raw, i) => {
    const trimmed = raw.trim();
    const key = trimmed.toUpperCase();
    if (trimmed !== '' && !seen.has(key)) {
      names.push(trimmed);
      seen.add(key);
    } else {
      let fallback = `col${i + 1}`;
      let fk = fallback.toUpperCase();
      let n = i + 1;
      while (seen.has(fk)) {
        n++;
        fallback = `col${n}`;
        fk = fallback.toUpperCase();
      }
      names.push(fallback);
      seen.add(fk);
    }
  });
  return names;
}

/** Double-quote a SQL identifier, escaping embedded `"` — safe for any column/table name regardless of leading digits, spaces, or symbols. */
function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

// ----- Editor support: auto-formatting and suggestions -----

/** All grammar keywords (case-insensitive) this UI actively suggests. Not exhaustive of SQLite's full dialect — see the follow-up note in docs/architecture.md. */
export const SQL_KEYWORDS: readonly string[] = [
  'SELECT',
  'FROM',
  'WHERE',
  'GROUP',
  'BY',
  'ORDER',
  'LIMIT',
  'AS',
  'AND',
  'OR',
  'NOT',
  'BETWEEN',
  'IN',
  'LIKE',
  'IS',
  'NULL',
  'ASC',
  'DESC',
  'DISTINCT',
  'HAVING',
  'JOIN',
  'LEFT',
  'INNER',
  'ON',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
];

/** Common read-only SQLite scalar/aggregate function names this UI actively suggests. Not exhaustive. */
export const SQL_FUNCTIONS: readonly string[] = [
  'ABS',
  'AVG',
  'COALESCE',
  'COUNT',
  'LENGTH',
  'LOWER',
  'MAX',
  'MIN',
  'ROUND',
  'SUM',
  'TRIM',
  'UPPER',
].sort();

const FORMAT_KEYWORD_SET = new Set(SQL_KEYWORDS);
const FORMAT_FUNCTION_SET = new Set(SQL_FUNCTIONS);
/** Clause keywords that start a new top-level line when formatting. */
const CLAUSE_START_KEYWORDS = new Set(['FROM', 'WHERE', 'GROUP', 'ORDER', 'LIMIT', 'HAVING']);

function formatTokenText(t: Token): string {
  switch (t.type) {
    case 'string':
      return `'${t.text.replace(/'/g, "''")}'`;
    case 'qident':
      return `"${t.text.replace(/"/g, '""')}"`;
    default:
      return t.text;
  }
}

/**
 * Best-effort auto-formatter: normalizes keyword/function casing and
 * whitespace, and breaks the query onto one line per SELECT item plus one
 * line per top-level clause (FROM/WHERE/GROUP BY/HAVING/ORDER BY/LIMIT).
 * Purely cosmetic (token-level, not a full parse), so it works the same
 * whether or not the query uses SQL beyond this UI's suggested keyword/
 * function list. `--`/`/* *\/` comments are discarded by the tokenizer and
 * so are dropped by formatting. Returns the input unchanged when it does not
 * even tokenize (reformatting text with e.g. an unterminated string would be
 * misleading).
 */
export function formatSqlQuery(query: string): string {
  let tokens: Token[];
  try {
    tokens = tokenize(query);
  } catch {
    return query;
  }
  const real = tokens.filter((t) => t.type !== 'eof');
  if (real.length === 0) return query;

  const INDENT = '  ';
  const lines: string[] = [];
  let line = '';
  let depth = 0;
  let inSelectList = true;
  let prev: Token | null = null;
  let atLineStart = true;

  const newLine = (prefix: string): void => {
    if (line !== '') lines.push(line);
    line = prefix;
    atLineStart = true;
  };

  for (let i = 0; i < real.length; i++) {
    const t = real[i];
    const next = real[i + 1];
    const isKeyword = FORMAT_KEYWORD_SET.has(t.upper);
    const isFunctionCall = t.type === 'ident' && FORMAT_FUNCTION_SET.has(t.upper) && next?.text === '(';
    const text = isKeyword || isFunctionCall ? t.upper : formatTokenText(t);

    if (depth === 0 && t.type === 'ident' && CLAUSE_START_KEYWORDS.has(t.upper)) {
      newLine(text);
      atLineStart = false;
      inSelectList = false;
      prev = t;
      continue;
    }
    if (depth === 0 && inSelectList && t.type === 'punct' && t.text === ',') {
      line += ',';
      newLine(INDENT);
      prev = t;
      continue;
    }

    const noSpace =
      atLineStart ||
      (prev !== null && prev.type === 'punct' && prev.text === '(') ||
      (t.type === 'punct' && [',', ')', ';'].includes(t.text)) ||
      (t.type === 'punct' &&
        t.text === '(' &&
        prev !== null &&
        prev.type === 'ident' &&
        FORMAT_FUNCTION_SET.has(prev.upper));
    line += (noSpace ? '' : ' ') + text;
    atLineStart = false;

    if (t.type === 'punct' && t.text === '(') depth++;
    if (t.type === 'punct' && t.text === ')') depth = Math.max(0, depth - 1);
    prev = t;
  }
  if (line !== '') lines.push(line);
  return lines.join('\n');
}

/** One suggested completion for the SQL editor. */
export interface SqlSuggestion {
  /** Text to display and insert (keywords/functions are uppercase; columns match the source header text). */
  text: string;
  kind: 'keyword' | 'function' | 'column';
}

/** Maximum suggestions returned for one cursor position. */
const SQL_MAX_SUGGESTIONS = 20;

/**
 * Prefix-match completions (case-insensitive) for the identifier immediately
 * before `cursorOffset`, drawn from SQL keywords, common function names, and
 * `columnNames`. Returns nothing for an empty prefix, or when the text
 * before the cursor does not even tokenize on its own (e.g. the cursor is
 * inside an unterminated string or quoted identifier — completing there
 * would insert into the literal rather than the query).
 */
export function suggestSqlCompletions(
  query: string,
  cursorOffset: number,
  columnNames: string[],
): SqlSuggestion[] {
  const before = query.slice(0, Math.max(0, Math.min(cursorOffset, query.length)));
  const match = /[A-Za-z0-9_]+$/.exec(before);
  if (!match) return [];
  try {
    tokenize(before);
  } catch {
    return [];
  }
  const upperPrefix = match[0].toUpperCase();

  const candidates: SqlSuggestion[] = [
    ...SQL_KEYWORDS.map((text): SqlSuggestion => ({ text, kind: 'keyword' })),
    ...SQL_FUNCTIONS.map((text): SqlSuggestion => ({ text, kind: 'function' })),
    ...Array.from(new Set(columnNames.map((c) => c.trim()).filter((c) => c !== ''))).map(
      (text): SqlSuggestion => ({ text, kind: 'column' }),
    ),
  ];
  const seen = new Set<string>();
  const matches: SqlSuggestion[] = [];
  for (const c of candidates) {
    const key = c.text.toUpperCase();
    if (key === upperPrefix || !key.startsWith(upperPrefix) || seen.has(key)) continue;
    seen.add(key);
    matches.push(c);
    if (matches.length >= SQL_MAX_SUGGESTIONS) break;
  }
  return matches;
}

// ----- sql.js (SQLite/WASM) engine boundary -----

/** Decode the embedded Base64 SQLite WASM binary locally (no fetch, no network, no locateFile). */
function decodeEmbeddedSqlJsWasm(base64: string = SQLJS_WASM_BASE64): ArrayBuffer {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes.buffer;
}

let sqlJsStatic: SqlJsStatic | null = null;
let initPromise: Promise<void> | null = null;

/**
 * Instantiate sql.js from the embedded Base64 binary. Idempotent — safe to
 * call from multiple places; every caller awaits the same promise (see
 * `src/main.ts`, which starts this in the background at startup, and
 * `src/app/commands/sql.ts`, which awaits it before every query run).
 * {@link runSqlQuery} throws {@link SqlQueryError} with code
 * `engineUnavailable` if called before this has resolved.
 */
export function initSqlEngine(): Promise<void> {
  initPromise ??= (async () => {
    sqlJsStatic = await initSqlJs({ wasmBinary: decodeEmbeddedSqlJsWasm() });
  })();
  return initPromise;
}

function requireSqlJs(): SqlJsStatic {
  if (!sqlJsStatic) {
    throw new SqlQueryError('engineUnavailable', 'the SQL engine is not ready yet', {}, null);
  }
  return sqlJsStatic;
}

/** Test hook: reset the cached sql.js instance/init promise. */
export function resetSqlEngineForTests(): void {
  sqlJsStatic = null;
  initPromise = null;
}

function toSqlValue(v: number | string | Uint8Array | null): SqlValue {
  if (v === null) return '';
  if (v instanceof Uint8Array) return bytesToHex(v);
  return v;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

function toSqliteError(e: unknown): SqlQueryError {
  const message = e instanceof Error ? e.message : String(e);
  return new SqlQueryError('sqliteError', message, { message });
}

/**
 * A cell's text is bound as a real SQLite number only when it is *exactly*
 * the canonical decimal form of that number (`String(Number(text)) ===
 * text`) — so `100` becomes numeric, but `007`, `1.50`, `1e2`, and `" 42 "`
 * are left as text and compare/sort lexicographically. This is deliberately
 * conservative: it never silently reformats a value the way it would be
 * displayed (leading zeros, trailing zeros, padding, exponent form are all
 * preserved verbatim), at the cost of not numerically comparing/sorting a
 * handful of unusual numeric-looking spellings — see docs/architecture.md.
 */
function canonicalNumericValue(text: string): number | null {
  if (text === '') return null;
  const n = Number(text);
  if (!Number.isFinite(n)) return null;
  return String(n) === text ? n : null;
}

/**
 * Bind value for one cell: blank → SQL NULL; a canonical numeric spelling →
 * a real SQLite number (so `>`/`BETWEEN`/`ORDER BY`/aggregates behave
 * numerically); anything else → the exact original text.
 */
function toBindValue(cell: string): number | string | null {
  if (cell === '') return null;
  const n = canonicalNumericValue(cell);
  return n !== null ? n : cell;
}

/**
 * Load `table` into a fresh, ephemeral in-memory SQLite database as a single
 * table named `data` (the fixed literal every query's `FROM` clause must
 * name). Column names are deduplicated/sanitized display names, always
 * double-quoted in the generated DDL — never the raw header text
 * interpolated unescaped. Every column is declared with SQLite's `BLOB`
 * type, which SQLite grants *no* column affinity — unlike `TEXT` (which
 * would force every value, numbers included, to compare lexicographically)
 * or `NUMERIC` (which would silently reformat numeric-looking text on
 * insert, losing e.g. leading zeros) — so each cell keeps exactly the
 * storage class {@link toBindValue} gave it. A blank source cell becomes SQL
 * `NULL` (so `IS NULL`/`COALESCE`/comparisons behave the way a spreadsheet's
 * "empty cell" naturally should), matching how the result is later mapped
 * back (`NULL` → `''`) for display/sheet output.
 */
function buildDatabase(table: SqlTable): { db: Database; sourceRows: number; sourceTruncated: boolean } {
  const SQL = requireSqlJs();
  const names = dedupeHeaderNames(table.headers);
  const sourceTruncated = table.rows.length > SQL_MAX_SOURCE_ROWS;
  const rows = sourceTruncated ? table.rows.slice(0, SQL_MAX_SOURCE_ROWS) : table.rows;

  const db = new SQL.Database();
  const columnsDdl = names.map((n) => `${quoteIdent(n)} BLOB`).join(', ');
  db.run(`CREATE TABLE ${quoteIdent('data')} (${columnsDdl})`);

  if (rows.length > 0) {
    const insertSql = `INSERT INTO ${quoteIdent('data')} (${names.map(quoteIdent).join(', ')}) VALUES (${names.map(() => '?').join(', ')})`;
    const insertStmt = db.prepare(insertSql);
    db.run('BEGIN');
    try {
      for (const row of rows) {
        const values = names.map((_, i) => toBindValue(row[i] ?? ''));
        insertStmt.run(values);
      }
      db.run('COMMIT');
    } catch (e) {
      db.run('ROLLBACK');
      insertStmt.free();
      db.close();
      throw e;
    }
    insertStmt.free();
  }

  return { db, sourceRows: rows.length, sourceTruncated };
}

/**
 * Read the picked source's table through the gated query, executed by
 * SQLite. Requires {@link initSqlEngine} to have already resolved.
 */
export function runSqlQuery(query: string, table: SqlTable): SqlQueryResult {
  const { body } = assertReadOnlyQuery(query);
  const { db, sourceRows, sourceTruncated } = buildDatabase(table);
  try {
    let matchedRows: number;
    try {
      const countStmt = db.prepare(`SELECT COUNT(*) FROM (\n${body}\n)`);
      try {
        countStmt.step();
        matchedRows = Number(countStmt.get()[0] ?? 0);
      } finally {
        countStmt.free();
      }
    } catch (e) {
      throw toSqliteError(e);
    }

    let columns: string[];
    const rows: SqlValue[][] = [];
    try {
      const stmt = db.prepare(`SELECT * FROM (\n${body}\n) LIMIT ${SQL_MAX_RESULT_ROWS}`);
      try {
        columns = stmt.getColumnNames();
        while (stmt.step()) {
          rows.push(stmt.get().map(toSqlValue));
        }
      } finally {
        stmt.free();
      }
    } catch (e) {
      throw toSqliteError(e);
    }

    return {
      columns,
      rows,
      sourceRows,
      sourceTruncated,
      matchedRows,
      truncated: rows.length < matchedRows,
    };
  } finally {
    db.close();
  }
}
