// SPDX-License-Identifier: MIT
// Build the Refrain Sheet landing page.
//
// Reads source files from site/ (template.html, i18n.js, and the
// static assets main.js, styles.css, favicon.svg, assets/), plus the
// design-system token stylesheets styles.css builds on, and writes a
// self-contained, deployable site to landing/ (gitignored — regenerated by
// this script, e.g. as the Cloudflare Pages build output directory):
//   landing/index.html      Japanese
//   landing/en/index.html   English
//
// Also writes landing/robots.txt and landing/_headers (noindex on
// *.pages.dev hosts), copies the static assets alongside the
// generated pages, and — when a public site URL is passed — canonical
// tags, hreflang alternates, absolute OG URLs and sitemap.xml.
//
//   node scripts/build-landing.mjs                      # relative URLs (preview)
//   node scripts/build-landing.mjs https://example.com/  # production
//
// This replaces the previous Python + BeautifulSoup implementation
// (landing/build.py) so the landing site no longer needs a Python
// toolchain: DOM manipulation uses jsdom, already a devDependency for the
// app's own jsdom-environment tests.

import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync, cpSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';
import { I18N } from '../site/i18n.js';
import { minifyCss } from './minify-css.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(root, 'site');
const landingDir = join(root, 'landing');

// styles.css is minified on the way out (see minify-css.mjs); the rest are
// copied verbatim.
const STATIC_ASSETS = ['main.js', 'consent.js', 'favicon.svg', 'assets'];

// The design-system stylesheets site/styles.css is written against: the
// foundations shared with the app, the app tokens (the hero demo draws the
// real app screen with the app's own values — brand guidelines D-42), the
// landing-only brand tokens, and the brand `rb-` components. They are
// prepended to styles.css so the site still ships one stylesheet with no
// @import. Regenerate them with design-system/v2/tools/build.mjs.
const DESIGN_SYSTEM_CSS = [
  'design-system/v2/foundations/css/foundations.css',
  'design-system/v2/app/css/app-tokens.css',
  'design-system/v2/brand/css/brand-tokens.css',
  'design-system/v2/brand/css/brand.css',
];

// The app's own UI strings. The hero demo takes every menu, dialog and
// status-bar label from here (`data-app-i18n`), so it always reads exactly
// like the real app (brand guidelines D-42).
const APP_I18N = {
  ja: JSON.parse(readFileSync(join(root, 'src/locales/ja.json'), 'utf8')),
  en: JSON.parse(readFileSync(join(root, 'src/locales/en.json'), 'utf8')),
};

const rawSite = process.argv[2];
const SITE = rawSite ? rawSite.replace(/\/+$/, '') + '/' : undefined;

const APP = 'https://app.refrain-sheet.com/';
const REPO = 'https://github.com/0x0da160/refrain-sheet';
const OG_IMG = 'assets/refrain-sheet-og-image.png';

// Each entry is a standalone template file rendered once per language. Only
// `index` gets the full SEO treatment (structured data, pretty root URLs);
// `privacy` and `terms` are simple flat-file pages served alongside it.
const PAGE_FILES = {
  index: { template: 'template.html', ja: 'index.html', en: 'en/index.html' },
  privacy: { template: 'privacy.html', ja: 'privacy.html', en: 'en/privacy.html' },
  terms: { template: 'terms.html', ja: 'terms.html', en: 'en/terms.html' },
};

const FEATURES = {
  ja: [
    '無編集で保存すると元ファイルとバイト単位で完全一致',
    '編集時に再シリアライズされるのは該当フィールドのバイト範囲だけ',
    'UTF-8 / Shift_JIS / CP932 / EUC-JP の自動判定と、文字コードを指定した開き直し',
    '保存時に文字コード・BOM・改行コードを個別に指定',
    '壊れたCSVを修復せず、行・列つきの診断を提示して開く',
    'RSFスプレッドシート（55関数・複数シート・フィルタ／並べ替え・セル書式設定・XLSXエクスポート）',
    '値を型推論で変換せず、先頭ゼロ・日付・長い番号を文字列のまま保持',
    '既存ファイルを既定で読み取り専用で開く保護モード',
    'データ入力規則・条件付き書式・数値の書式設定・SQLクエリの実行・比較／差分・セルコメント・コメントパネル',
    'CSVの読み込み・編集・保存はブラウザ内で処理（Google Drive連携を使う場合のみGoogleと通信）',
    'ホスト版アプリでのGoogle Drive連携（drive.fileスコープ）',
  ],
  en: [
    'Byte-identical output when a file is saved without edits',
    "Only the edited field's byte range is re-serialized",
    'Automatic detection of UTF-8, Shift_JIS, CP932 and EUC-JP, plus reopen with a chosen encoding',
    'Choose character encoding, BOM and line endings independently when saving',
    'Opens malformed CSV without repairing it, with row/column diagnostics',
    'RSF spreadsheet mode with 55 functions, multiple sheets, filtering/sorting, cell formatting and XLSX export',
    'No type inference: leading zeros, dates and long IDs stay as written',
    'Protect mode that opens existing files read-only by default',
    'Data validation, conditional formatting, number formatting, SQL queries, tab comparison/diff, cell comments and a comments panel',
    'CSV files are read, edited and saved inside the browser; the app contacts Google only when you use Google Drive',
    'Optional Google Drive open/save in the hosted app (drive.file scope)',
  ],
};
const OG_ALT = {
  ja: 'Refrain Sheet で Shift_JIS のCSVを開いた画面',
  en: 'Refrain Sheet showing a Shift_JIS CSV file',
};
const LOCALE = { ja: 'ja_JP', en: 'en_US' };

const rel = (path, depth) => '../'.repeat(depth) + path;
const absOrRel = (path, depth) => (SITE ? SITE + path : rel(path, depth));

/** Append a tag to `head`, with attributes set in sorted-key order (matches the
 * previous BeautifulSoup-generated markup, which serialized attributes sorted). */
function appendTag(doc, head, tagName, attrs) {
  const el = doc.createElement(tagName);
  for (const key of Object.keys(attrs).sort()) {
    el.setAttribute(key, attrs[key]);
  }
  head.appendChild(el);
}

/** Canonical URL for a page in a given language, or undefined without a SITE. */
function pageUrl(pageId, lang) {
  if (!SITE) return undefined;
  if (pageId === 'index') return SITE + (lang === 'ja' ? '' : 'en/');
  return SITE + PAGE_FILES[pageId][lang];
}

/**
 * Inline `<!-- @include partials/name.html -->` markers with the partial's
 * contents. Partials are plain HTML fragments under site/partials/, shared
 * between pages (header, footer, consent banner) or split out of the long
 * index template one section per file; they may not include each other.
 */
function resolveIncludes(html) {
  return html.replace(/<!--\s*@include\s+(partials\/[\w-]+\.html)\s*-->/g, (m, file) => {
    const partial = readFileSync(join(srcDir, file), 'utf8').replace(
      /^<!-- SPDX-License-Identifier: MIT -->\n/,
      '',
    );
    if (/@include/.test(partial)) throw new Error(`nested include in ${file}`);
    return partial;
  });
}

/** Set an element's text, turning each "\n" in the copy into a <br>. */
function setText(doc, el, text) {
  el.textContent = '';
  text.split('\n').forEach((line, i) => {
    if (i) el.appendChild(doc.createElement('br'));
    el.appendChild(doc.createTextNode(line));
  });
}

function build(pageId, lang) {
  const page = PAGE_FILES[pageId];
  const outRelPath = page[lang];
  const d = I18N[lang];
  const metaKey = pageId === 'index' ? '' : `${pageId}.`;
  const depth = (outRelPath.match(/\//g) ?? []).length;
  const template = resolveIncludes(readFileSync(join(srcDir, page.template), 'utf8'));
  const dom = new JSDOM(template);
  const doc = dom.window.document;
  doc.documentElement.setAttribute('lang', lang);

  // ---------- copy ----------
  for (const el of doc.querySelectorAll('[data-i18n]')) {
    const key = el.getAttribute('data-i18n');
    if (!(key in d)) throw new Error(`missing key: ${key}`);
    const attr = el.getAttribute('data-i18n-attr');
    if (attr) {
      el.setAttribute(attr, d[key]);
    } else if (!el.querySelector('*:not(br)')) {
      setText(doc, el, d[key]);
    }
  }

  // ---------- app UI strings (hero demo) ----------
  // `data-app-i18n-args` maps each {placeholder} to a key of this page's
  // own dictionary (the demo's sample file name, which differs per language).
  for (const el of doc.querySelectorAll('[data-app-i18n]')) {
    const key = el.getAttribute('data-app-i18n');
    const text = APP_I18N[lang][key];
    if (text === undefined) throw new Error(`missing app string: ${key}`);
    const args = JSON.parse(el.getAttribute('data-app-i18n-args') ?? '{}');
    const value = text.replace(/\{(\w+)\}/g, (m, name) => {
      if (!(name in args)) throw new Error(`missing argument {${name}} for app string: ${key}`);
      if (!(args[name] in d)) throw new Error(`missing key: ${args[name]}`);
      return d[args[name]];
    });
    el.textContent = value;
    el.removeAttribute('data-app-i18n');
    el.removeAttribute('data-app-i18n-args');
  }

  // ---------- language switcher ----------
  // `index` uses pretty directory URLs (its output already sits at the site
  // root / en/); other pages are flat files, so the switcher links directly
  // to the sibling file rather than to that page's own homepage.
  const otherLang = lang === 'ja' ? 'en' : 'ja';
  const hrefs =
    pageId === 'index'
      ? { ja: { ja: './', en: 'en/' }, en: { ja: '../', en: './' } }[lang]
      : { [lang]: './', [otherLang]: lang === 'ja' ? page.en : '../' + page.ja };
  for (const a of doc.querySelectorAll('.lang a')) {
    const code = a.getAttribute('data-lang');
    a.setAttribute('href', hrefs[code]);
    if (code === lang) {
      a.setAttribute('aria-current', 'page');
    } else {
      a.removeAttribute('aria-current');
    }
  }

  // ---------- relative asset paths ----------
  if (depth) {
    for (const el of doc.querySelectorAll('link, script, img')) {
      const attr = el.tagName === 'LINK' ? 'href' : 'src';
      const v = el.getAttribute(attr);
      if (v && !/^(https?:|#|\/|\.\.)/.test(v)) {
        el.setAttribute(attr, rel(v, depth));
      }
    }
    for (const el of doc.querySelectorAll('img[srcset], source[srcset]')) {
      const rewritten = el
        .getAttribute('srcset')
        .split(',')
        .map((candidate) => {
          const [url, descriptor] = candidate.trim().split(/\s+/, 2);
          const resolved = !/^(https?:|#|\/|\.\.)/.test(url) ? rel(url, depth) : url;
          return descriptor ? `${resolved} ${descriptor}` : resolved;
        })
        .join(', ');
      el.setAttribute('srcset', rewritten);
    }
  }

  // ---------- head ----------
  const head = doc.head;
  for (const el of head.querySelectorAll('[data-seo="1"]')) el.remove();

  const metaTitle = d[`${metaKey}meta.title`];
  const metaDesc = d[`${metaKey}meta.desc`];
  if (metaTitle === undefined) throw new Error(`missing key: ${metaKey}meta.title`);
  if (metaDesc === undefined) throw new Error(`missing key: ${metaKey}meta.desc`);
  doc.querySelector('title').textContent = metaTitle;
  head.querySelector('meta[name="description"]').setAttribute('content', metaDesc);

  appendTag(doc, head, 'meta', {
    name: 'robots',
    content: 'index,follow,max-image-preview:large,max-snippet:-1',
    'data-seo': '1',
  });
  appendTag(doc, head, 'meta', { name: 'author', content: '0x0da160', 'data-seo': '1' });

  const url = pageUrl(pageId, lang);
  if (url) {
    appendTag(doc, head, 'link', { rel: 'canonical', href: url, 'data-seo': '1' });
    appendTag(doc, head, 'link', {
      rel: 'alternate',
      hreflang: 'ja',
      href: pageUrl(pageId, 'ja'),
      'data-seo': '1',
    });
    appendTag(doc, head, 'link', {
      rel: 'alternate',
      hreflang: 'en',
      href: pageUrl(pageId, 'en'),
      'data-seo': '1',
    });
    appendTag(doc, head, 'link', {
      rel: 'alternate',
      hreflang: 'x-default',
      href: pageUrl(pageId, 'ja'),
      'data-seo': '1',
    });
    appendTag(doc, head, 'meta', { property: 'og:url', content: url, 'data-seo': '1' });
  }

  appendTag(doc, head, 'meta', { property: 'og:type', content: 'website', 'data-seo': '1' });
  appendTag(doc, head, 'meta', { property: 'og:site_name', content: 'Refrain Sheet', 'data-seo': '1' });
  appendTag(doc, head, 'meta', { property: 'og:title', content: metaTitle, 'data-seo': '1' });
  appendTag(doc, head, 'meta', { property: 'og:description', content: metaDesc, 'data-seo': '1' });
  appendTag(doc, head, 'meta', { property: 'og:image', content: absOrRel(OG_IMG, depth), 'data-seo': '1' });
  appendTag(doc, head, 'meta', { property: 'og:image:width', content: '1200', 'data-seo': '1' });
  appendTag(doc, head, 'meta', { property: 'og:image:height', content: '630', 'data-seo': '1' });
  appendTag(doc, head, 'meta', { property: 'og:image:alt', content: OG_ALT[lang], 'data-seo': '1' });
  appendTag(doc, head, 'meta', { property: 'og:locale', content: LOCALE[lang], 'data-seo': '1' });
  appendTag(doc, head, 'meta', {
    property: 'og:locale:alternate',
    content: LOCALE[lang === 'ja' ? 'en' : 'ja'],
    'data-seo': '1',
  });
  appendTag(doc, head, 'meta', { name: 'twitter:card', content: 'summary_large_image', 'data-seo': '1' });
  appendTag(doc, head, 'meta', { name: 'twitter:title', content: metaTitle, 'data-seo': '1' });
  appendTag(doc, head, 'meta', { name: 'twitter:description', content: metaDesc, 'data-seo': '1' });
  appendTag(doc, head, 'meta', {
    name: 'twitter:image',
    content: absOrRel(OG_IMG, depth),
    'data-seo': '1',
  });
  appendTag(doc, head, 'meta', { name: 'twitter:image:alt', content: OG_ALT[lang], 'data-seo': '1' });

  // ---------- structured data ----------
  // Only the app homepage carries SoftwareApplication/WebSite structured
  // data; privacy/terms are plain content pages with nothing to describe.
  if (pageId === 'index') {
    const app = {
      '@context': 'https://schema.org',
      '@type': ['SoftwareApplication', 'WebApplication'],
      name: 'Refrain Sheet',
      applicationCategory: 'BusinessApplication',
      applicationSubCategory: 'CSV editor',
      operatingSystem: 'Web browser (Chromium, Firefox, Safari)',
      browserRequirements:
        'Requires JavaScript. File System Access API needed for in-place overwrite (Chromium).',
      description: metaDesc,
      url: APP,
      installUrl: APP,
      downloadUrl: REPO + '/releases/',
      sameAs: [REPO],
      license: 'https://opensource.org/licenses/MIT',
      isAccessibleForFree: true,
      inLanguage: ['ja', 'en'],
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'JPY' },
      author: { '@type': 'Person', name: '0x0da160', url: 'https://github.com/0x0da160' },
      featureList: FEATURES[lang],
      screenshot: {
        '@type': 'ImageObject',
        contentUrl: absOrRel('assets/refrain-sheet-shift-jis-csv-editor.webp', depth),
        caption: d['csv.alt'],
      },
      image: absOrRel(OG_IMG, depth),
    };
    const graph = [app];
    const faq = [...doc.querySelectorAll('details.qa')].map((qa) => ({
      '@type': 'Question',
      name: qa.querySelector('summary').textContent.trim(),
      acceptedAnswer: { '@type': 'Answer', text: qa.querySelector('p').textContent.trim() },
    }));
    if (faq.length) {
      graph.push({ '@context': 'https://schema.org', '@type': 'FAQPage', inLanguage: lang, mainEntity: faq });
    }
    if (SITE) {
      graph.push({
        '@context': 'https://schema.org',
        '@type': 'WebSite',
        name: 'Refrain Sheet',
        url: SITE,
        inLanguage: lang,
      });
    }
    for (const obj of graph) {
      const s = doc.createElement('script');
      s.setAttribute('data-seo', '1');
      s.setAttribute('type', 'application/ld+json');
      s.textContent = JSON.stringify(obj, null, 2);
      head.appendChild(s);
    }
  }

  // jsdom's document-level serialization drops the whitespace between the
  // leading license comment, the doctype and <html> (it treats them as
  // adjacent Document children), and uppercases the doctype; restore the
  // template's line breaks and lowercase doctype there.
  const html = dom
    .serialize()
    .replace(
      '<!-- SPDX-License-Identifier: MIT --><!DOCTYPE html>',
      '<!-- SPDX-License-Identifier: MIT -->\n<!doctype html>\n\n',
    );

  const out = join(landingDir, outRelPath);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html, 'utf8');
  return out;
}

function copyStaticAssets() {
  mkdirSync(landingDir, { recursive: true });
  for (const name of STATIC_ASSETS) {
    cpSync(join(srcDir, name), join(landingDir, name), { recursive: true });
  }
  const css = [...DESIGN_SYSTEM_CSS.map((f) => join(root, f)), join(srcDir, 'styles.css')]
    .map((f) => readFileSync(f, 'utf8'))
    .join('\n');
  writeFileSync(join(landingDir, 'styles.css'), minifyCss(css), 'utf8');
}

function main() {
  copyStaticAssets();

  for (const pageId of Object.keys(PAGE_FILES)) {
    for (const lang of ['ja', 'en']) {
      console.warn('built', build(pageId, lang));
    }
  }

  let robots = 'User-agent: *\nAllow: /\n';
  if (SITE) robots += `\nSitemap: ${SITE}sitemap.xml\n`;
  writeFileSync(join(landingDir, 'robots.txt'), robots, 'utf8');

  // Cloudflare Pages `_headers`: keep every *.pages.dev host (the project's
  // pages.dev alias and each branch/PR preview) out of search indexes, so only
  // the custom domain is indexed. The custom domain matches neither pattern.
  const headers =
    'https://:project.pages.dev/*\n  X-Robots-Tag: noindex\n\n' +
    'https://:version.:project.pages.dev/*\n  X-Robots-Tag: noindex\n';
  writeFileSync(join(landingDir, '_headers'), headers, 'utf8');

  const sitemapPath = join(landingDir, 'sitemap.xml');
  if (SITE) {
    const urls = Object.keys(PAGE_FILES).flatMap((pageId) =>
      ['ja', 'en'].map((lang) => {
        const loc = pageUrl(pageId, lang);
        const altLangs = ['ja', 'en'];
        let alts = altLangs
          .map((l) => `\n    <xhtml:link rel="alternate" hreflang="${l}" href="${pageUrl(pageId, l)}"/>`)
          .join('');
        alts += `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${pageUrl(pageId, 'ja')}"/>`;
        return `  <url>\n    <loc>${loc}</loc>${alts}\n  </url>`;
      }),
    );
    writeFileSync(
      sitemapPath,
      '<?xml version="1.0" encoding="UTF-8"?>\n' +
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" ' +
        'xmlns:xhtml="http://www.w3.org/1999/xhtml">\n' +
        urls.join('\n') +
        '\n</urlset>\n',
      'utf8',
    );
    console.warn('built sitemap.xml');
  } else if (existsSync(sitemapPath)) {
    rmSync(sitemapPath);
  }
}

main();
