// SPDX-License-Identifier: MIT
// Renders a cloc report into the code-statistics table in README.md.
//
// Reads the JSON produced by `cloc --json` (path given as the first argument)
// and replaces ONLY the region between
//
//   <!-- code-stats:start -->   and   <!-- code-stats:end -->
//
// in README.md. Every byte outside those two markers is left untouched, and the
// markers themselves are preserved, so this can never rewrite prose it does not
// own. If either marker is missing, or they appear out of order, the script
// fails rather than guessing where the table belongs.
//
// The output is intentionally free of timestamps, commit hashes, cloc version
// numbers, and elapsed times. Those change on every run, which would make the
// generated diff non-empty even when the code has not changed at all — and the
// whole point of the workflow that calls this (.github/workflows/code-stats.yml)
// is that it acts only when there IS a real difference.
//
// Table formatting matches what Prettier produces for Markdown tables (padded
// cells, right-aligned numeric columns), so the rewritten README still passes
// `npm run format:check`.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const START = '<!-- code-stats:start -->';
const END = '<!-- code-stats:end -->';

const die = (msg) => {
  console.error(`code-stats: ${msg}`);
  process.exit(1);
};

const input = process.argv[2];
if (!input) die('usage: node scripts/code-stats.mjs <cloc-report.json>');

let report;
try {
  report = JSON.parse(readFileSync(input, 'utf8'));
} catch (err) {
  die(`could not read cloc JSON from ${input}: ${err.message}`);
}

// cloc's JSON is a flat object keyed by language name, plus two reserved keys:
// `header` (metadata we deliberately ignore) and `SUM` (the totals row).
const languages = Object.entries(report)
  .filter(([name]) => name !== 'header' && name !== 'SUM')
  .map(([name, v]) => ({
    name,
    files: v.nFiles ?? 0,
    blank: v.blank ?? 0,
    comment: v.comment ?? 0,
    code: v.code ?? 0,
  }))
  // Most code first; ties broken by name so the order is stable across runs
  // and a reordering never shows up as a spurious diff.
  .sort((a, b) => b.code - a.code || a.name.localeCompare(b.name, 'en'));

if (languages.length === 0) die('cloc reported no languages; refusing to write an empty table');

const sum = report.SUM ?? {
  nFiles: languages.reduce((n, l) => n + l.files, 0),
  blank: languages.reduce((n, l) => n + l.blank, 0),
  comment: languages.reduce((n, l) => n + l.comment, 0),
  code: languages.reduce((n, l) => n + l.code, 0),
};

const num = (n) => n.toLocaleString('en-US');

const header = ['Language', 'Files', 'Blank', 'Comment', 'Code'];
// Left-align the language name, right-align every count.
const alignRight = [false, true, true, true, true];
const rows = [
  ...languages.map((l) => [l.name, num(l.files), num(l.blank), num(l.comment), num(l.code)]),
  [
    '**Total**',
    `**${num(sum.nFiles ?? 0)}**`,
    `**${num(sum.blank)}**`,
    `**${num(sum.comment)}**`,
    `**${num(sum.code)}**`,
  ],
];

// Prettier pads every cell to the widest entry in its column, with a minimum
// delimiter width of three dashes; a right-aligned column ends its delimiter
// with a colon and pads its cells on the left.
const widths = header.map((h, i) => Math.max(3, h.length, ...rows.map((r) => r[i].length)));
const pad = (text, i) => (alignRight[i] ? text.padStart(widths[i], ' ') : text.padEnd(widths[i], ' '));
const line = (cells) => `| ${cells.map(pad).join(' | ')} |`;
const delimiter = `| ${widths
  .map((w, i) => (alignRight[i] ? `${'-'.repeat(w - 1)}:` : '-'.repeat(w)))
  .join(' | ')} |`;

const table = [line(header), delimiter, ...rows.map(line)].join('\n');

const generated = [
  START,
  '',
  '<!-- Generated by .github/workflows/code-stats.yml — do not edit by hand. -->',
  '',
  table,
  '',
  END,
].join('\n');

const readmePath = join(root, 'README.md');
const readme = readFileSync(readmePath, 'utf8');

const from = readme.indexOf(START);
const to = readme.indexOf(END);
if (from === -1) die(`README.md has no ${START} marker`);
if (to === -1) die(`README.md has no ${END} marker`);
if (to < from) die(`README.md has ${END} before ${START}`);
if (readme.indexOf(START, from + 1) !== -1 || readme.indexOf(END, to + 1) !== -1) {
  die('README.md has duplicate code-stats markers; refusing to guess which region to replace');
}

const updated = readme.slice(0, from) + generated + readme.slice(to + END.length);
if (updated === readme) {
  console.warn('code-stats: README.md is already up to date.');
  process.exit(0);
}

writeFileSync(readmePath, updated);
console.warn(
  `code-stats: updated README.md (${languages.length} languages, ${num(sum.code)} lines of code).`,
);
