// SPDX-License-Identifier: MIT
// Embed sql.js's compiled SQLite WASM binary into the source tree as a
// Base64 payload — the same pattern scripts/embed-wasm.mjs uses for the
// Rust performance core.
//
// Reads node_modules/sql.js/dist/sql-wasm.wasm (present after a plain
// `npm ci`, no extra toolchain required) and generates
// src/wasm-gen/sqljs-wasm-payload.ts, the WASM binary as a Base64 string.
// The generated file is committed so `npm run build`/`npm run test` work
// without re-running this script; re-run it (`npm run build:sqljs`) after
// bumping the pinned `sql.js` version in package.json.
//
// The sql.js JS runtime itself (dist/sql-wasm.js) is imported directly from
// the `sql.js` package, like any other npm dependency (see
// docs/architecture.md "The SQL query engine") — only the WASM binary needs
// embedding, and `src/core/sql-engine.ts` always instantiates it from these
// decoded bytes via the `wasmBinary` config option, never `locateFile()`.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const wasmPath = join(root, 'node_modules', 'sql.js', 'dist', 'sql-wasm.wasm');
const outDir = join(root, 'src', 'wasm-gen');

const wasmBytes = readFileSync(wasmPath);
const base64 = wasmBytes.toString('base64');
const banner = `// @generated by scripts/embed-sqljs.mjs — do not edit.\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, 'sqljs-wasm-payload.ts'),
  banner +
    `// The compiled sql.js (SQLite) WebAssembly binary (${wasmBytes.length} bytes),\n` +
    `// embedded as Base64 so the distribution needs no separate .wasm asset and\n` +
    `// no network access. Decoded and instantiated locally at runtime — see\n` +
    `// src/core/sql-engine.ts.\n` +
    `export const SQLJS_WASM_BYTE_LENGTH = ${wasmBytes.length};\n` +
    `export const SQLJS_WASM_BASE64 =\n  '${base64}';\n`,
);

console.warn(`embed-sqljs: embedded ${wasmBytes.length} bytes of WASM (${base64.length} Base64 chars)`);
