// SPDX-License-Identifier: MIT
// Embed every vendored local-assistant model (see scripts/model-catalog.mjs)
// into the source tree as chunked Base64 payloads, the same pattern
// scripts/embed-wasm.mjs uses for the Rust/WASM core
// (src/wasm-gen/wasm-payload.ts) — just applied to much larger, multi-file
// artifacts, one per model.
//
// For each model, reads .model-cache/<cacheDirName> (populated by
// `npm run fetch:model`) and generates src/llm-gen/<genDirName>/:
//   - model-payload/<file>.partNNN.ts : each source file's bytes, Base64
//     encoded and split into chunks well under GitHub's 100MB-per-file push
//     limit (each source file may need several chunk files; small files get
//     exactly one),
//   - model-manifest.ts               : imports every chunk and lists, per
//     source file, its original byte length, a SHA-256 checksum, and its
//     ordered chunks — so runtime code can reassemble and verify each file
//     before writing it into Cache Storage.
//
// The generated files are committed, like src/wasm-gen/, so the app builds
// and tests without a network fetch or the Python/TVM model-compilation
// toolchain. This script is not run in CI.
//
// Embeds every model in scripts/model-catalog.mjs by default; pass a model
// `key` as the first CLI argument to (re-)embed only that one, mirroring
// scripts/fetch-model.mjs's single-model mode.

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MODELS } from './model-catalog.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const onlyKey = process.argv[2];
const targets = onlyKey ? MODELS.filter((m) => m.key === onlyKey) : MODELS;
if (onlyKey && targets.length === 0) {
  console.error(`embed-model: no model with key "${onlyKey}" in scripts/model-catalog.mjs`);
  process.exit(1);
}

// Raw bytes per chunk file before Base64 inflation (~1.33x). 8 MiB raw is
// ~10.7 MiB of Base64 text per generated .ts file — comfortably under
// GitHub's 100MB single-file push limit with a lot of headroom, and small
// enough that tsc/Vite parse each file quickly.
const CHUNK_RAW_BYTES = 8 * 1024 * 1024;

const banner = `// @generated by scripts/embed-model.mjs — do not edit.\n`;

function sanitize(name) {
  return name.replace(/[^a-zA-Z0-9]/g, '_');
}

for (const model of targets) {
  const srcDir = join(root, '.model-cache', model.cacheDirName ?? '.');
  const outDir = join(root, 'src', 'llm-gen', model.genDirName ?? '.');
  const chunkDir = join(outDir, 'model-payload');

  // The wasm kernel is already the last entry of `files` when it comes from
  // the model's own HF repo (wasmUrl is null); otherwise it was fetched
  // separately and must be appended.
  const files = model.wasmUrl ? [...model.files, model.wasmFileName] : model.files;

  rmSync(chunkDir, { recursive: true, force: true });
  mkdirSync(chunkDir, { recursive: true });

  const manifestImports = [];
  const manifestEntries = [];

  for (const file of files) {
    const bytes = readFileSync(join(srcDir, file));
    const sha256 = createHash('sha256').update(bytes).digest('hex');
    const ident = sanitize(file);

    const chunkVarNames = [];
    let partIndex = 0;
    for (let offset = 0; offset < bytes.length; offset += CHUNK_RAW_BYTES) {
      const chunk = bytes.subarray(offset, Math.min(offset + CHUNK_RAW_BYTES, bytes.length));
      const base64 = chunk.toString('base64');
      const varName = `chunk_${ident}_${partIndex}`;
      const fileName = `${file}.part${String(partIndex).padStart(3, '0')}.ts`;

      writeFileSync(
        join(chunkDir, fileName),
        banner +
          `// Base64 chunk ${partIndex} of "${file}" (${chunk.length} of ${bytes.length} bytes).\n` +
          `export const CHUNK_BASE64 =\n  '${base64}';\n`,
      );

      manifestImports.push(
        `import { CHUNK_BASE64 as ${varName} } from './model-payload/${fileName.replace(/\.ts$/, '')}';`,
      );
      chunkVarNames.push(varName);
      partIndex += 1;
    }

    manifestEntries.push(
      `  {\n` +
        `    name: '${file}',\n` +
        `    byteLength: ${bytes.length},\n` +
        `    sha256: '${sha256}',\n` +
        `    chunks: [${chunkVarNames.join(', ')}],\n` +
        `  },`,
    );

    console.warn(`embed-model: [${model.key}] embedded ${file} (${bytes.length} bytes, ${chunkVarNames.length} chunk(s))`);
  }

  // Relative depth back to src/app/llm/ from this manifest's own directory
  // (src/llm-gen/ for the legacy flat layout, src/llm-gen/<genDirName>/
  // otherwise) — one extra `../` when the model has its own subdirectory.
  const typeImportPath = model.genDirName ? '../../app/llm/model-file-entry' : '../app/llm/model-file-entry';

  const manifestTs =
    banner +
    `// The vendored "${model.key}" local-assistant model (see docs/llm-model.md),\n` +
    `// embedded as chunked Base64 so the distribution needs no network access.\n` +
    `// Each entry's chunks are decoded and concatenated, then verified against\n` +
    `// \`sha256\`, before being written into Cache Storage — see\n` +
    `// src/app/llm/cache-prepopulate.ts.\n\n` +
    `import type { ModelFileEntry } from '${typeImportPath}';\n\n` +
    manifestImports.join('\n') +
    `\n\nexport type { ModelFileEntry };\n\n` +
    `export const MODEL_FILES: readonly ModelFileEntry[] = [\n${manifestEntries.join('\n')}\n];\n`;

  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'model-manifest.ts'), manifestTs);

  const chunkFileCount = readdirSync(chunkDir).length;
  console.warn(
    `embed-model: [${model.key}] wrote model-manifest.ts referencing ${chunkFileCount} chunk file(s) in ${chunkDir}`,
  );
}
