// SPDX-License-Identifier: MIT
// Embed the compiled WASM binary into the source tree as a Base64 payload.
//
// Reads the wasm-pack output (wasm/pkg/) and generates src/wasm-gen/:
//   - refrain_csv_core.js / .d.ts : the wasm-bindgen JS glue, patched so it
//     can never fall back to fetching a .wasm file by URL,
//   - wasm-payload.ts             : the WASM binary as a Base64 string.
//
// The generated files are committed so the TypeScript build and tests work
// without a local Rust toolchain; CI regenerates them and fails if they are
// stale. The final distribution instantiates WebAssembly exclusively from
// the embedded Base64 bytes — it never fetches a separately hosted .wasm.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkgDir = join(root, 'wasm', 'pkg');
const outDir = join(root, 'src', 'wasm-gen');

const wasmBytes = readFileSync(join(pkgDir, 'refrain_csv_core_bg.wasm'));
let glue = readFileSync(join(pkgDir, 'refrain_csv_core.js'), 'utf8');
const dts = readFileSync(join(pkgDir, 'refrain_csv_core.d.ts'), 'utf8');

// The wasm-bindgen glue falls back to `new URL('..._bg.wasm', import.meta.url)`
// when no module is passed. That must never happen in this project (the
// distribution embeds the binary and never fetches a .wasm), and bundlers
// eagerly turn that pattern into an emitted .wasm asset. Replace the
// fallback with a hard error; fail loudly if the glue shape ever changes.
const urlFallback = /module_or_path\s*=\s*new URL\('refrain_csv_core_bg\.wasm',\s*import\.meta\.url\);/;
if (!urlFallback.test(glue)) {
  console.error(
    'embed-wasm: expected URL fallback not found in wasm-bindgen glue; update scripts/embed-wasm.mjs',
  );
  process.exit(1);
}
glue = glue.replace(
  urlFallback,
  "throw new Error('refrain-csv-core: WASM must be instantiated from embedded bytes, never fetched by URL');",
);

const banner = `// @generated by scripts/embed-wasm.mjs — do not edit.\n`;
const base64 = wasmBytes.toString('base64');

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'refrain_csv_core.js'), banner + glue);
writeFileSync(join(outDir, 'refrain_csv_core.d.ts'), banner + dts);
writeFileSync(
  join(outDir, 'wasm-payload.ts'),
  banner +
    `// The compiled refrain-csv-core WebAssembly binary (${wasmBytes.length} bytes),\n` +
    `// embedded as Base64 so the distribution needs no separate .wasm asset and\n` +
    `// no network access. Decoded and instantiated locally at runtime.\n` +
    `export const WASM_BYTE_LENGTH = ${wasmBytes.length};\n` +
    `export const WASM_BASE64 =\n  '${base64}';\n`,
);

console.warn(`embed-wasm: embedded ${wasmBytes.length} bytes of WASM (${base64.length} Base64 chars)`);
