// SPDX-License-Identifier: MIT
// Embed the vendored local-assistant model into the source tree as chunked
// Base64 payloads, the same pattern scripts/embed-wasm.mjs uses for the
// Rust/WASM core (src/wasm-gen/wasm-payload.ts) — just applied to a much
// larger, multi-file artifact.
//
// Reads .model-cache/ (populated by `npm run fetch:model`) and generates
// src/llm-gen/:
//   - model-payload/<file>.partNNN.ts : each source file's bytes, Base64
//     encoded and split into chunks well under GitHub's 100MB-per-file push
//     limit (each source file may need several chunk files; small files get
//     exactly one),
//   - model-manifest.ts               : imports every chunk and lists, per
//     source file, its original byte length, a SHA-256 checksum, and its
//     ordered chunks — so runtime code can reassemble and verify each file
//     before writing it into Cache Storage.
//
// Only 8 of the upstream repository's 12 files are vendored. WebLLM's own
// loading path (read from its published lib/index.js — see
// src/app/llm/model-source.ts for the exact cache keys this mirrors) never
// requests `tokenizer.model`, `tokenizer_config.json`, `added_tokens.json`,
// or `tensor-cache-b16.json`: `mlc-chat-config.json`'s `tokenizer_files`
// lists `tokenizer.json` too, and `asyncLoadTokenizer()` prefers it over
// `tokenizer.model` whenever both are listed, so the other tokenizer files
// are dead weight for this runtime. `tensor-cache-b16.json` is an alternate
// (bf16) manifest the q4f32_1 quantization this app vendors does not use.
//
// The generated files are committed, like src/wasm-gen/, so the app builds
// and tests without a network fetch or the Python/TVM model-compilation
// toolchain. This script is not run in CI.

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(root, '.model-cache');
const outDir = join(root, 'src', 'llm-gen');
const chunkDir = join(outDir, 'model-payload');

// Raw bytes per chunk file before Base64 inflation (~1.33x). 8 MiB raw is
// ~10.7 MiB of Base64 text per generated .ts file — comfortably under
// GitHub's 100MB single-file push limit with a lot of headroom, and small
// enough that tsc/Vite parse each file quickly.
const CHUNK_RAW_BYTES = 8 * 1024 * 1024;

// Source files, in the order the manifest lists them. Must match
// src/app/llm/model-source.ts's MODEL_FILES list exactly.
const FILES = [
  'mlc-chat-config.json',
  'tensor-cache.json',
  'params_shard_0.bin',
  'params_shard_1.bin',
  'params_shard_2.bin',
  'params_shard_3.bin',
  'tokenizer.json',
  'gemma3-270m-japanese-q4f32_1-ctx4k-webgpu.wasm',
];

const banner = `// @generated by scripts/embed-model.mjs — do not edit.\n`;

function sanitize(name) {
  return name.replace(/[^a-zA-Z0-9]/g, '_');
}

rmSync(chunkDir, { recursive: true, force: true });
mkdirSync(chunkDir, { recursive: true });

const manifestImports = [];
const manifestEntries = [];

for (const file of FILES) {
  const bytes = readFileSync(join(srcDir, file));
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  const ident = sanitize(file);

  const chunkVarNames = [];
  let partIndex = 0;
  for (let offset = 0; offset < bytes.length; offset += CHUNK_RAW_BYTES) {
    const chunk = bytes.subarray(offset, Math.min(offset + CHUNK_RAW_BYTES, bytes.length));
    const base64 = chunk.toString('base64');
    const varName = `chunk_${ident}_${partIndex}`;
    const fileName = `${file}.part${String(partIndex).padStart(3, '0')}.ts`;

    writeFileSync(
      join(chunkDir, fileName),
      banner +
        `// Base64 chunk ${partIndex} of "${file}" (${chunk.length} of ${bytes.length} bytes).\n` +
        `export const CHUNK_BASE64 =\n  '${base64}';\n`,
    );

    manifestImports.push(`import { CHUNK_BASE64 as ${varName} } from './model-payload/${fileName.replace(/\.ts$/, '')}';`);
    chunkVarNames.push(varName);
    partIndex += 1;
  }

  manifestEntries.push(
    `  {\n` +
      `    name: '${file}',\n` +
      `    byteLength: ${bytes.length},\n` +
      `    sha256: '${sha256}',\n` +
      `    chunks: [${chunkVarNames.join(', ')}],\n` +
      `  },`,
  );

  console.warn(`embed-model: embedded ${file} (${bytes.length} bytes, ${chunkVarNames.length} chunk(s))`);
}

const manifestTs =
  banner +
  `// The vendored local-assistant model (see docs/llm-model.md), embedded as\n` +
  `// chunked Base64 so the distribution needs no network access. Each entry's\n` +
  `// chunks are decoded and concatenated, then verified against \`sha256\`,\n` +
  `// before being written into Cache Storage — see src/app/llm/cache-prepopulate.ts.\n\n` +
  manifestImports.join('\n') +
  `\n\nexport interface ModelFileEntry {\n` +
  `  readonly name: string;\n` +
  `  readonly byteLength: number;\n` +
  `  readonly sha256: string;\n` +
  `  readonly chunks: readonly string[];\n` +
  `}\n\n` +
  `export const MODEL_FILES: readonly ModelFileEntry[] = [\n${manifestEntries.join('\n')}\n];\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'model-manifest.ts'), manifestTs);

const chunkFileCount = readdirSync(chunkDir).length;
console.warn(`embed-model: wrote model-manifest.ts referencing ${chunkFileCount} chunk file(s) in src/llm-gen/model-payload/`);
