// @generated by scripts/embed-model.mjs — do not edit.
// The vendored "smollm2-135m-instruct" local-assistant model (see docs/llm-model.md),
// embedded as chunked Base64 so the distribution needs no network access.
// Each entry's chunks are decoded and concatenated, then verified against
// `sha256`, before being written into Cache Storage — see
// src/app/llm/cache-prepopulate.ts.

import type { ModelFileEntry } from '../../app/llm/model-file-entry';

import { CHUNK_BASE64 as chunk_mlc_chat_config_json_0 } from './model-payload/mlc-chat-config.json.part000';
import { CHUNK_BASE64 as chunk_tensor_cache_json_0 } from './model-payload/tensor-cache.json.part000';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_0 } from './model-payload/params_shard_0.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_1 } from './model-payload/params_shard_0.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_2 } from './model-payload/params_shard_0.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_3 } from './model-payload/params_shard_0.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_4 } from './model-payload/params_shard_0.bin.part004';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_5 } from './model-payload/params_shard_0.bin.part005';
import { CHUNK_BASE64 as chunk_params_shard_0_bin_6 } from './model-payload/params_shard_0.bin.part006';
import { CHUNK_BASE64 as chunk_params_shard_1_bin_0 } from './model-payload/params_shard_1.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_1_bin_1 } from './model-payload/params_shard_1.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_1_bin_2 } from './model-payload/params_shard_1.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_1_bin_3 } from './model-payload/params_shard_1.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_2_bin_0 } from './model-payload/params_shard_2.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_2_bin_1 } from './model-payload/params_shard_2.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_2_bin_2 } from './model-payload/params_shard_2.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_2_bin_3 } from './model-payload/params_shard_2.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_3_bin_0 } from './model-payload/params_shard_3.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_3_bin_1 } from './model-payload/params_shard_3.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_3_bin_2 } from './model-payload/params_shard_3.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_3_bin_3 } from './model-payload/params_shard_3.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_4_bin_0 } from './model-payload/params_shard_4.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_4_bin_1 } from './model-payload/params_shard_4.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_4_bin_2 } from './model-payload/params_shard_4.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_4_bin_3 } from './model-payload/params_shard_4.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_5_bin_0 } from './model-payload/params_shard_5.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_5_bin_1 } from './model-payload/params_shard_5.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_5_bin_2 } from './model-payload/params_shard_5.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_5_bin_3 } from './model-payload/params_shard_5.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_6_bin_0 } from './model-payload/params_shard_6.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_6_bin_1 } from './model-payload/params_shard_6.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_6_bin_2 } from './model-payload/params_shard_6.bin.part002';
import { CHUNK_BASE64 as chunk_params_shard_6_bin_3 } from './model-payload/params_shard_6.bin.part003';
import { CHUNK_BASE64 as chunk_params_shard_7_bin_0 } from './model-payload/params_shard_7.bin.part000';
import { CHUNK_BASE64 as chunk_params_shard_7_bin_1 } from './model-payload/params_shard_7.bin.part001';
import { CHUNK_BASE64 as chunk_params_shard_7_bin_2 } from './model-payload/params_shard_7.bin.part002';
import { CHUNK_BASE64 as chunk_tokenizer_json_0 } from './model-payload/tokenizer.json.part000';
import { CHUNK_BASE64 as chunk_SmolLM2_135M_Instruct_q0f16_cs1k_webgpu_wasm_0 } from './model-payload/SmolLM2-135M-Instruct-q0f16_cs1k-webgpu.wasm.part000';

export type { ModelFileEntry };

export const MODEL_FILES: readonly ModelFileEntry[] = [
  {
    name: 'mlc-chat-config.json',
    byteLength: 2018,
    sha256: '84fa8cda47c443589d05c7295339b0c58c15d964e7f2df53873366187789bb59',
    chunks: [chunk_mlc_chat_config_json_0],
  },
  {
    name: 'tensor-cache.json',
    byteLength: 70279,
    sha256: 'bb1307859901ebe833a1ad9f25b5a2babed8bbcfe8ea1d7e5b64db52e1c17149',
    chunks: [chunk_tensor_cache_json_0],
  },
  {
    name: 'params_shard_0.bin',
    byteLength: 56623104,
    sha256: 'dbe321b43856cffd6920fc39ce1e9750556c3698aae47ca561652548d23dc2cd',
    chunks: [chunk_params_shard_0_bin_0, chunk_params_shard_0_bin_1, chunk_params_shard_0_bin_2, chunk_params_shard_0_bin_3, chunk_params_shard_0_bin_4, chunk_params_shard_0_bin_5, chunk_params_shard_0_bin_6],
  },
  {
    name: 'params_shard_1.bin',
    byteLength: 30091392,
    sha256: '90eb8da289949ce6ea2fceec85228966fcc6b8cd962504ce0a58e21a0e308f51',
    chunks: [chunk_params_shard_1_bin_0, chunk_params_shard_1_bin_1, chunk_params_shard_1_bin_2, chunk_params_shard_1_bin_3],
  },
  {
    name: 'params_shard_2.bin',
    byteLength: 32966784,
    sha256: 'ffb047fe03c824f7f32fb7abad18c6265ec31400b2b98e32d442deda8b030ce8',
    chunks: [chunk_params_shard_2_bin_0, chunk_params_shard_2_bin_1, chunk_params_shard_2_bin_2, chunk_params_shard_2_bin_3],
  },
  {
    name: 'params_shard_3.bin',
    byteLength: 30754944,
    sha256: '8feb2e304125627dc231c30d4457fe9c5df5709b9e2858046ac3463175401ef7',
    chunks: [chunk_params_shard_3_bin_0, chunk_params_shard_3_bin_1, chunk_params_shard_3_bin_2, chunk_params_shard_3_bin_3],
  },
  {
    name: 'params_shard_4.bin',
    byteLength: 32966784,
    sha256: '1cda5ecde438a850307b9490514e58235c64d640399fa68a4c0c28fcff84a1e4',
    chunks: [chunk_params_shard_4_bin_0, chunk_params_shard_4_bin_1, chunk_params_shard_4_bin_2, chunk_params_shard_4_bin_3],
  },
  {
    name: 'params_shard_5.bin',
    byteLength: 30754944,
    sha256: '6df9612bec9d030861635bd33f3cbeef82eba604fed050b168252f965916de35',
    chunks: [chunk_params_shard_5_bin_0, chunk_params_shard_5_bin_1, chunk_params_shard_5_bin_2, chunk_params_shard_5_bin_3],
  },
  {
    name: 'params_shard_6.bin',
    byteLength: 32966784,
    sha256: '3cdabc62da6bf632d0000920cf0785f93a7b38140a2ab1096f8e029dc2382ebb',
    chunks: [chunk_params_shard_6_bin_0, chunk_params_shard_6_bin_1, chunk_params_shard_6_bin_2, chunk_params_shard_6_bin_3],
  },
  {
    name: 'params_shard_7.bin',
    byteLength: 21905280,
    sha256: 'ef917ee0421e0fa69bcde5bfc7ba50a96028756bb30181004d34b3babceb88fc',
    chunks: [chunk_params_shard_7_bin_0, chunk_params_shard_7_bin_1, chunk_params_shard_7_bin_2],
  },
  {
    name: 'tokenizer.json',
    byteLength: 2104556,
    sha256: '9ca9acddb6525a194ec8ac7a87f24fbba7232a9a15ffa1af0c1224fcd888e47c',
    chunks: [chunk_tokenizer_json_0],
  },
  {
    name: 'SmolLM2-135M-Instruct-q0f16_cs1k-webgpu.wasm',
    byteLength: 5420101,
    sha256: '124201e7d550944c578f67c813d74b861bee2b45c8478a694634599ba5364e64',
    chunks: [chunk_SmolLM2_135M_Instruct_q0f16_cs1k_webgpu_wasm_0],
  },
];
